name: ✨ Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the sections below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem would this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: |
        I would like to be able to...

        Example usage:
        ```python
        generator.new_feature(...)
        ```
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - Tabular Generation (CTGAN, TVAE, Gaussian Copula)
        - Time Series Generation
        - Text Generation
        - Privacy Features
        - Evaluation & Metrics
        - Multi-table Synthesis
        - CLI
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, examples, or references.
